### ISSUE TITLE
:

### ISSUE THREAD

**Issue by UMecamat** [kriswiner/VEML6070#1]
Hi Kris, 
thank you so much for your work on VEML6070. 
I am playing around with this sensor wired to both Arduino Uno and ESP8266-01 and I have a doubt on UV radiant power acquisition at line 108:

Serial.print("UV radiant power = "); Serial.print((float)steps*5.0); Serial.println(" microWatts/cm*cm");

Can you explain me why steps are multiplied by a factor of 5, please?

Perhaps you will find interesting the following work:
https://polaridad.es/sensor-ultravioleta-uv-i2c-veml6070-arduino/
Unfortunately is in Spanish, but the author substantially suggest to calculate a coefficient value to obtain a more precise UV raw counts according to the number of UVI (i.e., using a 270K ohm resistance and IT_1, the coefficient can be obtained as follow: 2055(max value)/11(max UVI)=186,818182 (coefficient). In his code the UV raw counts corrected is than obtained by dividing the UV raw counts by the coefficient. I saw that you applied a coefficient of correction for the VEML6075... any suggestion for VEML6070?

Thank you in advance

**Comment by kriswiner** [comment]
I think the conversion factor of 5 uW/CM2 per step is in the data sheet or
what Vishay told me, not sure.

**Comment by UMecamat** [comment]
Thanks a lot for the very fast reply
